import type { Metadata } from "next";
import { Smooch_Sans } from "next/font/google";
import "./globals.css";
import Navigation from "@/components/Navigation";


const smoochSans = Smooch_Sans({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${smoochSans.variable} antialiased`}
      >
        <Navigation/>
        <main className="container mx-auto">
        {children}
        </main>
      </body>
    </html>
  );
}
